#include "AlyssaCore.hpp"
#include "WeightedFusion/WeightedFusion.hpp"
#include "voice/ElevenLabsTTS.hpp"
#include "AlyssaMemoryHandler.hpp"
#include "IExpert.hpp"
#include <memory>
#include <map>
#include <vector>
#include <unordered_map>

/**
 * @class CoreIntegration
 * @brief Main orchestration class for the Alyssa AI system using Mixture of Experts (MoE) architecture.
 * 
 * This class integrates multiple specialized AI models (experts) with weighted fusion capabilities,
 * memory management, and text-to-speech functionality. It serves as the central controller for
 * processing user inputs through different expert models and generating coherent responses.
 * 
 * Key features:
 * - Mixture of Experts (MoE) architecture with specialized models
 * - Weighted fusion of expert contributions
 * - Long-term memory integration
 * - Context switching between experts
 * - TTS (Text-to-Speech) integration
 * - Dynamic history management
 */
class CoreIntegration {
private:
    std::unique_ptr<alyssa_core::AlyssaCore> core_instance;           ///< Base model instance (1B)
    std::unique_ptr<alyssa_fusion::WeightedFusion> fusion_engine;    ///< Weighted fusion engine
    std::shared_ptr<Embedder> embedder;                             ///< Embedding generator for semantic analysis
    std::unique_ptr<alyssa_memory::AlyssaMemoryManager> memory_manager; ///< Long-term memory manager
    
    /// @brief Map of registered expert models with their unique IDs
    std::unordered_map<std::string, std::unique_ptr<alyssa_experts::IExpert>> experts;
    
    /// @brief Conversation history for each expert
    std::unordered_map<std::string, std::vector<llama_chat_message>> expert_histories;
    
    std::string active_expert_in_cache;    ///< Currently active expert in KV cache
    bool initialized;                      ///< System initialization status

public:
    /**
     * @brief Default constructor.
     * @details Initializes the CoreIntegration system with default values.
     */
    CoreIntegration();
    
    /**
     * @brief Destructor.
     * @details Cleans up all allocated resources and expert histories.
     */
    ~CoreIntegration();

    /**
     * @brief Set the user's name for personalized interactions.
     * @param name The user's name to be stored in memory.
     */
    void set_user_name(const std::string& name);
    
    std::string user_name = ""; ///< Current user's name for personalization
    
    /**
     * @brief Initialize the complete Alyssa AI system.
     * @param base_model_path Path to the base model configuration file.
     * @return true if initialization succeeded, false otherwise.
     * @details Loads models, initializes experts, memory system, and fusion engine.
     */
    bool initialize(const std::string& base_model_path);
    
    // =========================================================================
    // Main Processing Methods
    // =========================================================================
    
    /**
     * @brief Process user input using standard MoE architecture.
     * @param input User's text input.
     * @param tts ElevenLabsTTS instance for voice synthesis.
     * @return Response generated by the AI system.
     * @details Uses emotional analysis, memory retrieval, and Alyssa model for final response.
     */
    std::string think(const std::string& input, ElevenLabsTTS& tts);
    
    /**
     * @brief Process user input with weighted fusion and TTS.
     * @param input User's text input.
     * @param tts ElevenLabsTTS instance for voice synthesis.
     * @return Fused response from multiple experts.
     * @details Runs expert committee, applies weighted fusion, and generates voice output.
     */
    std::string think_with_fusion(const std::string& input, ElevenLabsTTS& tts);
    
    /**
     * @brief Process user input with weighted fusion without TTS.
     * @param input User's text input.
     * @return Fused response from multiple experts.
     * @details Same as think_with_fusion but without voice synthesis.
     */
    std::string think_with_fusion_ttsless(const std::string& input);
    
    // =========================================================================
    // Expert Management Methods
    // =========================================================================
    
    /**
     * @brief Register a new expert model with the system.
     * @param expert Unique pointer to the expert implementation.
     */
    void register_expert(std::unique_ptr<alyssa_experts::IExpert> expert);
    
    /**
     * @brief Remove an expert from the system.
     * @param expert_id Unique identifier of the expert to remove.
     */
    void remove_expert(const std::string& expert_id);
    
    /**
     * @brief Check if an expert is registered.
     * @param expert_id Unique identifier of the expert.
     * @return true if expert exists, false otherwise.
     */
    bool has_expert(const std::string& expert_id) const;
    
    /**
     * @brief Validate if input fits within expert's context window.
     * @param prompt Input text to validate.
     * @param expert_id Expert identifier.
     * @return true if context size is sufficient, false otherwise.
     */
    bool validate_context_size(const std::string& prompt, const std::string& expert_id);
    
    /**
     * @brief Detect emotional content in input using heuristics.
     * @param input Text to analyze for emotional content.
     * @return Detected emotion as string (e.g., "neutralidade", "curiosidade").
     */
    std::string detect_emotion_with_heuristics(const std::string& input);

    /**
     * @brief Calculate coherence metric for expert committee responses.
     * @param contributions Vector of contributions from different experts.
     * @return Coherence score between 0.0 (incoherent) and 1.0 (fully coherent).
     */
    float calculate_committee_coherence(const std::vector<alyssa_fusion::ExpertContribution>& contributions);
    
    /**
     * @brief Determine if interaction should be stored in long-term memory.
     * @param input User's input text.
     * @param response System's response text.
     * @return true if worth storing in memory, false for small talk/noise.
     */
    bool should_store_in_memory(const std::string& input, const std::string& response);

    // =========================================================================
    // Utility Methods
    // =========================================================================
    
    /**
     * @brief Generate fused input for Alyssa model from expert contributions.
     * @param original_input Original user input.
     * @param contributions Vector of expert contributions.
     * @param emotion Detected emotion for context.
     * @return Formatted prompt with expert thoughts and memory context.
     */
    std::string generate_fused_input(
        const std::string& original_input,
        const std::vector<alyssa_fusion::ExpertContribution>& contributions,
        const std::string& emotion
    );
    
    /**
     * @brief Log source awareness information.
     * @param source Source identifier (expert ID).
     * @param message Message to log.
     */
    void log_source_awareness(const std::string& source, const std::string& message);

    /**
     * @brief Clear all caches including KV cache and expert histories.
     */
    void clear_all_cache() {
        clear_kv_cache();
        for (auto& pair : expert_histories) {
            for (auto& msg : pair.second) {
                free((char*)msg.content);
            }
            pair.second.clear();
        }
        std::cout << "[Orquestrador] Todos os caches limpos." << std::endl;
    }

private:
    // =========================================================================
    // Expert Execution Methods
    // =========================================================================
    
    /**
     * @brief Execute a specific expert with input processing.
     * @param expert_id Identifier of expert to run.
     * @param input Text input for the expert.
     * @param use_tts Enable TTS synthesis for streaming.
     * @param tts Pointer to TTS instance (can be nullptr).
     * @return Expert's response as string.
     */
    std::string run_expert(
        const std::string& expert_id,
        const std::string& input,
        bool use_tts = false,
        ElevenLabsTTS* tts = nullptr
    );

    /**
     * @brief Check if two expert signals are compatible.
     * @param signal1 First expert signal.
     * @param signal2 Second expert signal.
     * @return true if signals are compatible, false if contradictory.
     */
    bool are_signals_compatible(const std::string& signal1, const std::string& signal2);
    
    /**
     * @brief Calculate string similarity using Jaccard index.
     * @param str1 First string.
     * @param str2 Second string.
     * @return Similarity score between 0.0 (no similarity) and 1.0 (identical).
     */
    float calculate_string_similarity(const std::string& str1, const std::string& str2);
    
    /**
     * @brief Determine if input is small talk/social pleasantry.
     * @param input Text to analyze.
     * @return true if input is small talk, false if substantive content.
     */
    bool is_small_talk(const std::string& input);
    
    // =========================================================================
    // Committee and Fusion Methods
    // =========================================================================
    
    /**
     * @brief Run committee of experts in parallel.
     * @param expert_ids Vector of expert identifiers to include in committee.
     * @param input Text input for all experts.
     * @return Vector of contributions from each expert.
     */
    std::vector<alyssa_fusion::ExpertContribution> run_expert_committee(
        const std::vector<std::string>& expert_ids,
        const std::string& input
    );
    
    // =========================================================================
    // History and Cache Management
    // =========================================================================
    
    /**
     * @brief Manage expert history with dynamic size limits.
     * @param expert_id Expert identifier.
     * @param history Reference to expert's conversation history.
     * @details Archives old messages to LTM when history exceeds limit.
     */
    void manage_dynamic_history(
        const std::string& expert_id,
        std::vector<llama_chat_message>& history
    );
    
    /**
     * @brief Calculate dynamic history limit based on expert and emotional state.
     * @param expert_id Expert identifier.
     * @return Maximum number of messages to keep in history.
     */
    size_t calculate_history_limit(const std::string& expert_id);
    
    /**
     * @brief Clear KV cache for current expert.
     */
    void clear_kv_cache();
    
    /**
     * @brief Switch active expert context in KV cache.
     * @param new_expert_id Expert to switch to.
     */
    void switch_expert_context(const std::string& new_expert_id);
    
    // =========================================================================
    // Reflection and Action Methods
    // =========================================================================
    
    /**
     * @brief Execute an action command.
     * @param command Action command to execute.
     */
    void act(const std::string& command);
    
    /**
     * @brief Perform system reflection/self-analysis.
     */
    void reflect();

public:
    /**
     * @brief Run interactive command-line interface.
     * @details Continuously processes user input until exit command.
     */
    void run_interactive_loop();
};
